
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
