name: CI/CD Pipeline

# Trigger the workflow on pushes to main and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Build Docker image for the backend
      - name: Build Backend Image
        run: |
          docker build -t backend ./backend

      # Step 3: Build Docker image for the frontend
      - name: Build Frontend Image
        run: |
          docker build -t frontend ./frontend

      # Step 4: Run backend tests
      - name: Run Backend Tests
        run: |
          docker run backend npm test

      # Step 5: Run frontend tests
      - name: Run Frontend Tests
        run: |
          docker run frontend npm test

