name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test with Docker Compose
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml up -d
          docker-compose exec backend npm test  # Run backend tests
          docker-compose exec frontend npm test  # Run frontend tests
        # Stop the containers after testing
        env:
          REACT_APP_BACKEND_URL: http://localhost:5000

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 172.105.77.29
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/more-project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
